[package]
name = "package-core"
repository.workspace = true
license.workspace = true
edition.workspace = true
workspace = ".."

[dependencies]
tokio.workspace = true
crossbeam.workspace = true

[lints]
workspace = true