#!/bin/bash

# Real-time Fallback Debugging - Step by Step Guide
echo "🔍 FiqhAdvisor Real-time Debugging Guide"
echo "========================================"
echo ""

echo "📱 STEP 1: Prepare Your Environment"
echo "-----------------------------------"
echo "1. Connect your Android device/emulator"
echo "2. Enable USB Debugging"
echo "3. Run: adb devices"
echo ""
read -p "✅ Device connected? Press Enter to continue..."

echo ""
echo "🧹 STEP 2: Clear Logs and Start Monitoring"
echo "------------------------------------------"
echo "Run this command in your terminal:"
echo ""
echo "adb logcat -c && adb logcat -v time | grep -E \"(FiqhAIViewModel|FiqhAIManager|🔍|✅|❌|⚠️|💥|System not initialized|Native library)\" --color=always"
echo ""
read -p "✅ Monitoring started? Press Enter to continue..."

echo ""
echo "🏗️ STEP 3: Build and Install App"
echo "--------------------------------"
echo "Run these commands:"
echo ""
echo "cd /mnt/d/Engineer/web3/rizilab/fiqhadvisor/android"
echo "./gradlew installDebug"
echo ""
read -p "✅ App installed? Press Enter to continue..."

echo ""
echo "🚀 STEP 4: Launch App"
echo "--------------------"
echo "Run this command:"
echo ""
echo "adb shell am start -n com.rizilab.fiqhadvisor/.MainActivity"
echo ""
echo "👀 Watch your monitoring terminal for startup messages!"
echo ""
read -p "✅ App launched? Press Enter to continue..."

echo ""
echo "🧪 STEP 5: Test AI Query"
echo "-----------------------"
echo "1. In the app, go to the chat interface"
echo "2. Type a test query like: 'Bitcoin'"
echo "3. Send the message"
echo ""
echo "👀 Watch your monitoring terminal for these key messages:"
echo ""
echo "✅ SUCCESS INDICATORS:"
echo "   - 🔍 Analyzing token: Bitcoin"
echo "   - ✅ System initialized, calling fiqhManager.analyzeToken()"
echo "   - ✅ Token analysis successful for Bitcoin"
echo ""
echo "❌ FAILURE INDICATORS:"
echo "   - ⚠️ System not initialized, providing fallback response"
echo "   - ❌ Failed to initialize AI system"
echo "   - UnsatisfiedLinkError or library loading errors"
echo ""
read -p "✅ Query tested? Press Enter to continue..."

echo ""
echo "📊 STEP 6: Analyze Results"
echo "-------------------------"
echo "Based on what you saw in the logs, identify the issue:"
echo ""
echo "🟢 If you saw '✅ Token analysis successful':"
echo "   → AI system is working! The issue might be elsewhere."
echo ""
echo "🟡 If you saw '⚠️ System not initialized':"
echo "   → FiqhAIManager initialization is failing."
echo "   → Check for initialization error messages."
echo ""
echo "🔴 If you saw 'UnsatisfiedLinkError' or library errors:"
echo "   → Native library (libfiqh_core.so) is not loading."
echo "   → Check APK contents and build configuration."
echo ""
echo "🔵 If you saw no FiqhAIViewModel messages at all:"
echo "   → The ViewModel might not be getting called."
echo "   → Check UI integration and method calls."
echo ""

echo ""
echo "🔍 STEP 7: Specific Issue Commands"
echo "---------------------------------"
echo ""
echo "For Native Library Issues:"
echo "adb logcat | grep -E \"(library|JNI|uniffi|libfiqh_core|UnsatisfiedLinkError)\""
echo ""
echo "For Initialization Issues:"
echo "adb logcat | grep -E \"(FiqhAIManager|initialization|failed|System not initialized)\""
echo ""
echo "For UniFFI Issues:"
echo "adb logcat | grep -E \"(uniffi|rust|binding)\""
echo ""
echo "For Recent Errors:"
echo "adb logcat -d | grep -E \"(ERROR|FATAL)\" | grep -i fiqh | tail -10"
echo ""

echo ""
echo "📝 STEP 8: Save Logs for Analysis"
echo "--------------------------------"
echo "To save logs for detailed analysis:"
echo ""
echo "adb logcat -d > fiqhadvisor_debug_$(date +%Y%m%d_%H%M%S).log"
echo ""
echo "This saves all recent logs to a file for review."
echo ""

echo ""
echo "🎯 READY TO START!"
echo "=================="
echo "1. Open a terminal and run the monitoring command from Step 2"
echo "2. Follow steps 3-6 while watching the monitoring output"
echo "3. Report back what you see in the logs!"
echo ""
echo "The key is to watch for the emoji indicators (🔍✅❌⚠️💥) that will show"
echo "exactly where the process is failing."