[bindings.kotlin]
package_name = "com.rizilab.averroes.averroescore"
cdylib_name = "averroes_core"
generate_immutable_records = true

[bindings.swift]
module_name = "AverroesCore"
ffi_module_name = "AverroesCoreFFI"
ffi_module_filename = "averroescore"
generate_immutable_records = true
omit_argument_labels = false
